version: "3.5"

services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - 27017:27017
    command: mongod
  server:
    container_name: server
    build: ./server
    ports:
      - 5000:5000
    stdin_open: true
    command: npm start